export const DrinkConstants = {
    UPDATE_DRINKS: 'DRINKS_UPDATE',
    CLEAR_DRINKS: 'DRINKS_CLEAR',
    CLEAR_DRINK_TIME: 'DRINK_TIME_CLEAR',
    UPDATE_DRINK_TYPES: 'DRINKS_TYPES_UPDATE',
    CLEAR_DRINK_TYPES: 'DRINK_TYPES_CLEAR',
};
